# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registrar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(blank=True, max_length=120)),
                ('Apellido', models.CharField(blank=True, max_length=120)),
                ('Telefono', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
