# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visitadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrar',
            name='Telefono',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
