# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-19 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citas', models.CharField(max_length=50)),
                ('paciente', models.CharField(max_length=50)),
                ('doctor', models.CharField(max_length=50)),
                ('medicina', models.CharField(max_length=50)),
                ('cantidad_medicina', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='registrodoctor',
            name='especialidad',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
