# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-19 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctores', '0002_auto_20170119_0454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Historial_medico', models.CharField(max_length=50)),
                ('citas_futuras', models.CharField(max_length=50)),
            ],
        ),
    ]
