# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-24 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctores', '0003_historial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itinerario',
            old_name='paciente',
            new_name='paciente_itinerario',
        ),
        migrations.AddField(
            model_name='itinerario',
            name='observacion',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
