# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Medicamentos', '0003_registrar_visitador_id'),
        ('pacientes', '0002_remove_paciente_edad'),
        ('Doctores', '0004_auto_20170124_0057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerario',
            name='cantidad_medicina',
        ),
        migrations.RemoveField(
            model_name='itinerario',
            name='citas',
        ),
        migrations.RemoveField(
            model_name='itinerario',
            name='medicina',
        ),
        migrations.RemoveField(
            model_name='itinerario',
            name='paciente_itinerario',
        ),
        migrations.AddField(
            model_name='itinerario',
            name='fecha',
            field=models.DateField(default='2017-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itinerario',
            name='idFamilia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Medicamentos.Registrar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itinerario',
            name='paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itinerario',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctores.RegistroDoctor'),
        ),
    ]
