# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 22:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctores', '0006_auto_20170429_2049'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Historial',
        ),
    ]
