# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-16 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='familia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primerApellido', models.CharField(max_length=45)),
                ('segundoApellido', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('fechaNacimiento', models.DateField()),
                ('telefono', models.CharField(blank=True, max_length=8)),
                ('genero', models.CharField(max_length=9)),
                ('edad', models.IntegerField()),
                ('tipoSangre', models.CharField(max_length=3)),
                ('dpi', models.CharField(max_length=30)),
                ('cui', models.CharField(max_length=30)),
                ('idFamilia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.familia')),
            ],
        ),
    ]
