# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Visitadores', '0001_initial'),
        ('Medicamentos', '0002_remove_registrar_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrar',
            name='Visitador_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Visitadores.Registrar'),
            preserve_default=False,
        ),
    ]
